### ISSUE TITLE
Update npm package to 0.11

### ISSUE THREAD

**Issue by i3games** [purescript-contrib/node-purescript-bin#42] opened 2017-04-07 14:09 UTC
The package on npm is still at 0.10.7, which now breaks new installations, see e.g. [https://groups.google.com/forum/#!topic/purescript/HkOp7_zwqbU](https://groups.google.com/forum/#!topic/purescript/HkOp7_zwqbU)

**Comment by shinnn** [comment] 2017-04-07 14:49
Duplicate of https://github.com/purescript-contrib/node-purescript-bin/issues/41

**Closed by shinnn** 2017-04-07 14:49 UTC
