### ISSUE TITLE
`npm install purescript` not working (w/ defaults anyway)

### ISSUE THREAD

**Issue by jbrownson** [purescript-contrib/node-purescript-bin#24] opened 2016-05-29 16:11 UTC
I'm not a npm/web expert, but w/ a "standard" and up to date npm configuration on OS X is failing with the below errors. It looks like this was fixed in https://github.com/purescript-contrib/node-purescript-bin/commit/f2bf2b3ce88366d27e13e35639ca018057b66638, but when I try to install it seems to be picking up an old version. I don't know how all of this works, maybe it needs to be tagged or released or something?

```
$ npm install purescript -g
/usr/local/bin/psc -> /usr/local/lib/node_modules/purescript/bin/psc.js
/usr/local/bin/psc-bundle -> /usr/local/lib/node_modules/purescript/bin/psc-bundle.js
/usr/local/bin/psc-ide-client -> /usr/local/lib/node_modules/purescript/bin/psc-ide-client.js
/usr/local/bin/psc-docs -> /usr/local/lib/node_modules/purescript/bin/psc-docs.js
/usr/local/bin/psc-ide-server -> /usr/local/lib/node_modules/purescript/bin/psc-ide-server.js
/usr/local/bin/psc-publish -> /usr/local/lib/node_modules/purescript/bin/psc-publish.js
/usr/local/bin/psci -> /usr/local/lib/node_modules/purescript/bin/psci.js

> purescript@0.8.5 postinstall /usr/local/lib/node_modules/purescript
> node --harmony_destructuring lib/install.js

node: bad option: --harmony_destructuring
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/6.2.0/bin/node" "/usr/local/bin/npm" "install" "purescript" "-g"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! purescript@0.8.5 postinstall: `node --harmony_destructuring lib/install.js`
npm ERR! Exit status 9
npm ERR! 
npm ERR! Failed at the purescript@0.8.5 postinstall script 'node --harmony_destructuring lib/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the prescript package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --harmony_destructuring lib/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs purescript
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls prescript
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jake/Downloads/flux-challenge/submissions/spicydonuts/pux/npm-debug.log
```

**Comment by kRITZCREEK** [comment] 2016-05-29 17:03
for node 6 you currently need to do `npm install purescript@next`. This will still give you purescript 0.8.5.

**Comment by jbrownson** [comment] 2016-05-29 19:46
Is this the desired behavior? I just used defaults installing node from brew, a pretty standard path for folks coming to purescript for the first time, could we streamline it?

**Comment by shinnn** [comment] 2016-05-30 01:51
Duplicate of https://github.com/purescript-contrib/node-purescript-bin/issues/22

**Closed by shinnn** 2016-05-30 01:51 UTC
